name: Publish Common Lint Config

on:
  push:
    branches:
      - master
    paths:
      - packages/common/package.json

jobs:
  publish:
    name: Publish
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        run: |
          cd packages
          cd common
          yarn npm publish
