name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, test, publish
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUBPAT }}'
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Get Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Publish
        run: |
          npm publish

      - name: Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Published `eslint-config-rafflebox` to Github - <https://github.com/rafflebox-technologies-inc/eslint-config-rafflebox/commit/${{ steps.vars.outputs.sha_short }}|${{ steps.vars.outputs.sha_short }}>"}' https://hooks.slack.com/services/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

      - name: Failed
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$GITHUB_WORKFLOW"' Failed for `${{ github.event.repository.name }}` - <'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'|View Run>"}' https://hooks.slack.com/services/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
